name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn lint
#      - name: Check docs
#        run: yarn docs && \[ -z "$(git status --porcelain)" \] || (echo "Docs are out-of-sync. Please run 'yarn docs' and include doc updates in the same commit that changed the code." && exit 1)
